---
apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app: scrape-agent-scheduled
spec:
  restartPolicy: Never
  serviceAccount: scrape-scheduler
  serviceAccountName: scrape-scheduler
  automountServiceAccountToken: true
  volumes:
  - name: google-cloud-key
    secret:
      defaultMode: 420
      secretName: google-cloud-key
  containers:
  - name: scrape-agents
    image: eu.gcr.io/qfx-data/scrape-agents-dev:latest
    imagePullPolicy: Always
    resources:
      requests: 
        cpu: 500m
        memory: 200Mi
      limits:
        cpu: "1"
        memory: 512Mi
    volumeMounts:
    - name: google-cloud-key
      mountPath: /keys/
    envFrom:
    - configMapRef:
        name: scrape-agents-config
    command: ["/bin/sh"]
    # args: ["-c", "COMMAND"]

